from __future__ import annotations

import csv
import json
from io import StringIO
from pathlib import Path

import httpx


def to_json(results: dict[str, dict]) -> str:
    return json.dumps(results, indent=2)


def to_csv(results: dict[str, dict]) -> str:
    buffer = StringIO()
    writer = csv.writer(buffer)
    writer.writerow(["platform", "status", "url", "title", "emails"])
    for name, info in sorted(results.items()):
        emails = ", ".join(info.get("emails", [])) if info.get("emails") else ""
        writer.writerow([
            name,
            info["status"],
            info["url"],
            info.get("title", ""),
            emails,
        ])
    return buffer.getvalue()


def to_markdown(results: dict[str, dict], username: str) -> str:
    lines = [
        f"# Argis scan results for `@{username}`",
        "",
        "| Platform | Status | URL |",
        "|---|---|---|",
    ]
    for name, info in sorted(results.items()):
        lines.append(f"| {name} | {info['status']} | {info['url']} |")
    return "\n".join(lines) + "\n"


def to_html(results: dict[str, dict], username: str) -> str:
    found = sum(1 for r in results.values() if r["status"] == "FOUND")
    total = len(results)

    rows = ""
    for name, info in sorted(results.items()):
        status = info["status"]
        status_colors = {
            "FOUND": "#22c55e",
            "NOT_FOUND": "#ef4444",
            "BLOCKED": "#a855f7",
            "TIMEOUT": "#eab308",
            "UNKNOWN": "#f97316",
        }
        color = status_colors.get(status, "#6b7280")
        title = info.get("title") or ""
        emails = info.get("emails") or []
        email_str = ", ".join(f'<a href="mailto:{e}">{e}</a>' for e in emails) if emails else ""
        rows += f"""<tr>
            <td>{name}</td>
            <td><span style="color:{color};font-weight:bold">{status}</span></td>
            <td><a href="{info['url']}" target="_blank">{info['url'][:60]}...</a></td>
            <td>{title}</td>
            <td>{email_str}</td>
        </tr>\n"""

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Argis scan — @{username}</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 1200px; margin: 0 auto; padding: 20px; background: #0f172a; color: #e2e8f0; }}
  h1 {{ color: #38bdf8; border-bottom: 2px solid #1e293b; padding-bottom: 10px; }}
  .summary {{ background: #1e293b; padding: 15px 20px; border-radius: 8px; margin: 20px 0; }}
  .summary span {{ font-size: 1.2em; }}
  .found {{ color: #22c55e; font-weight: bold; }}
  table {{ width: 100%; border-collapse: collapse; margin-top: 20px; }}
  th, td {{ padding: 10px 12px; text-align: left; border-bottom: 1px solid #1e293b; }}
  th {{ background: #1e293b; color: #94a3b8; text-transform: uppercase; font-size: 0.8em; letter-spacing: 0.05em; }}
  tr:hover {{ background: #1e293b; }}
  a {{ color: #38bdf8; text-decoration: none; }}
  a:hover {{ text-decoration: underline; }}
  .footer {{ margin-top: 30px; color: #64748b; font-size: 0.85em; text-align: center; }}
</style>
</head>
<body>
<h1>🔍 Argis scan — @{username}</h1>
<div class="summary">
  <span class="found">{found}</span> / {total} platforms show an active profile
</div>
<table>
<thead>
  <tr><th>Platform</th><th>Status</th><th>URL</th><th>Title</th><th>Emails</th></tr>
</thead>
<tbody>
{rows}
</tbody>
</table>
<div class="footer">Generated by Argis OSINT Scanner</div>
</body>
</html>"""


FORMATTERS = {
    "json": lambda results, username: to_json(results),
    "csv": lambda results, username: to_csv(results),
    "markdown": to_markdown,
    "html": to_html,
}


def export_results(results: dict[str, dict], username: str, fmt: str, out_path: Path) -> Path:
    formatter = FORMATTERS.get(fmt)
    if formatter is None:
        raise ValueError(f"Unsupported export format: {fmt}")
    content = formatter(results, username)
    out_path.write_text(content, encoding="utf-8")
    return out_path


def to_json_stream(results: dict[str, dict]) -> str:
    lines = []
    for name, info in sorted(results.items()):
        entry = {"platform": name, **info}
        lines.append(json.dumps(entry))
    return "\n".join(lines)


async def send_webhook(
    url: str,
    results: dict[str, dict],
    username: str,
    webhook_type: str = "slack",
) -> bool:
    found = sum(1 for r in results.values() if r["status"] == "FOUND")
    total = len(results)

    if webhook_type == "slack":
        payload = {
            "text": f"*Argis scan complete — @{username}*\n> {found}/{total} platforms found",
            "attachments": [
                {
                    "color": "good" if found > 0 else "warning",
                    "fields": [
                        {"title": "Username", "value": username, "short": True},
                        {"title": "Profiles Found", "value": str(found), "short": True},
                        {"title": "Total Scanned", "value": str(total), "short": True},
                    ],
                }
            ],
        }
    elif webhook_type == "discord":
        color = 0x22C55E if found > 0 else 0xF97316
        payload = {
            "embeds": [
                {
                    "title": f"Argis scan — @{username}",
                    "color": color,
                    "fields": [
                        {"name": "Username", "value": username, "inline": True},
                        {"name": "Profiles Found", "value": str(found), "inline": True},
                        {"name": "Total Scanned", "value": str(total), "inline": True},
                    ],
                    "footer": {"text": "Argis OSINT Scanner"},
                }
            ]
        }
    else:
        payload = {
            "username": username,
            "found": found,
            "total": total,
            "results": {k: v["status"] for k, v in results.items()},
        }

    async with httpx.AsyncClient(timeout=10.0) as client:
        try:
            resp = await client.post(url, json=payload)
            return resp.is_success
        except httpx.RequestError:
            return False
