from __future__ import annotations

import csv
import html as htmlmod
import json
import zipfile
from io import BytesIO, StringIO
from pathlib import Path

import httpx


def to_json(results: dict[str, dict]) -> str:
    return json.dumps(results, indent=2)


def to_csv(results: dict[str, dict]) -> str:
    buffer = StringIO()
    writer = csv.writer(buffer)
    writer.writerow(["platform", "status", "url", "title", "emails"])
    for name, info in sorted(results.items()):
        emails = ", ".join(info.get("emails", [])) if info.get("emails") else ""
        writer.writerow([
            name,
            info["status"],
            info["url"],
            info.get("title", ""),
            emails,
        ])
    return buffer.getvalue()


def to_markdown(results: dict[str, dict], username: str) -> str:
    lines = [
        f"# Argis scan results for `@{username}`",
        "",
        "| Platform | Status | URL |",
        "|---|---|---|",
    ]
    for name, info in sorted(results.items()):
        lines.append(f"| {name} | {info['status']} | {info['url']} |")
    return "\n".join(lines) + "\n"


def to_html(results: dict[str, dict], username: str) -> str:
    found = sum(1 for r in results.values() if r["status"] == "FOUND")
    total = len(results)

    rows = ""
    for name, info in sorted(results.items()):
        status = info["status"]
        status_colors = {
            "FOUND": "#22c55e",
            "NOT_FOUND": "#ef4444",
            "BLOCKED": "#a855f7",
            "TIMEOUT": "#eab308",
            "UNKNOWN": "#f97316",
        }
        color = status_colors.get(status, "#6b7280")
        title = info.get("title") or ""
        emails = info.get("emails") or []
        email_str = ", ".join(f'<a href="mailto:{e}">{e}</a>' for e in emails) if emails else ""
        rows += f"""<tr>
            <td>{name}</td>
            <td><span style="color:{color};font-weight:bold">{status}</span></td>
            <td><a href="{info['url']}" target="_blank">{info['url'][:60]}...</a></td>
            <td>{title}</td>
            <td>{email_str}</td>
        </tr>\n"""

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Argis scan — @{username}</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 1200px; margin: 0 auto; padding: 20px; background: #0f172a; color: #e2e8f0; }}
  h1 {{ color: #38bdf8; border-bottom: 2px solid #1e293b; padding-bottom: 10px; }}
  .summary {{ background: #1e293b; padding: 15px 20px; border-radius: 8px; margin: 20px 0; }}
  .summary span {{ font-size: 1.2em; }}
  .found {{ color: #22c55e; font-weight: bold; }}
  table {{ width: 100%; border-collapse: collapse; margin-top: 20px; }}
  th, td {{ padding: 10px 12px; text-align: left; border-bottom: 1px solid #1e293b; }}
  th {{ background: #1e293b; color: #94a3b8; text-transform: uppercase; font-size: 0.8em; letter-spacing: 0.05em; }}
  tr:hover {{ background: #1e293b; }}
  a {{ color: #38bdf8; text-decoration: none; }}
  a:hover {{ text-decoration: underline; }}
  .footer {{ margin-top: 30px; color: #64748b; font-size: 0.85em; text-align: center; }}
</style>
</head>
<body>
<h1>🔍 Argis scan — @{username}</h1>
<div class="summary">
  <span class="found">{found}</span> / {total} platforms show an active profile
</div>
<table>
<thead>
  <tr><th>Platform</th><th>Status</th><th>URL</th><th>Title</th><th>Emails</th></tr>
</thead>
<tbody>
{rows}
</tbody>
</table>
<div class="footer">Generated by Argis OSINT Scanner</div>
</body>
</html>"""


def to_txt(results: dict, username: str) -> str:
    lines = [f"Argis scan results for @{username}", "=" * 40, ""]
    found = {p: r for p, r in sorted(results.items()) if r.get("status") == "FOUND"}
    lines.append(f"Found: {len(found)} / {len(results)} platforms\n")
    for p, r in found.items():
        conf = r.get("confidence", "?")
        lines.append(f"[{conf}%] {p}")
        lines.append(f"  URL: {r['url']}")
        if r.get("title"):
            lines.append(f"  Title: {r['title']}")
        if r.get("emails"):
            lines.append(f"  Emails: {', '.join(r['emails'])}")
        lines.append("")
    return "\n".join(lines)


def to_ndjson(results: dict, username: str) -> str:
    lines = []
    for name, info in sorted(results.items()):
        entry = {"username": username, "platform": name, **info}
        lines.append(json.dumps(entry, ensure_ascii=False))
    return "\n".join(lines)


def _xml_esc(s: str) -> str:
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")


def to_xmind(results: dict, username: str) -> bytes:
    found = {p: r for p, r in results.items() if r.get("status") == "FOUND"}
    by_cat: dict[str, list] = {}
    for p, r in found.items():
        by_cat.setdefault(r.get("category", "uncategorized"), []).append((p, r))

    topics = ""
    for cat, items in sorted(by_cat.items()):
        subtopics = ""
        for p, r in items:
            subtopics += f'<topic><title>{_xml_esc(p)}</title><note>{_xml_esc(r["url"])}</note></topic>'
        topics += f'<topic><title>{_xml_esc(cat)} ({len(items)})</title><children><topics type="attached">{subtopics}</topics></children></topic>'

    content_xml = f"""<?xml version="1.0" encoding="UTF-8"?>
<xmap-content xmlns="urn:xmind:xmap:xmlns:content:2.0">
  <sheet>
    <topic><title>@{_xml_esc(username)} ({len(found)} found)</title>
      <children><topics type="attached">{topics}</topics></children>
    </topic>
  </sheet>
</xmap-content>"""

    meta_xml = '<?xml version="1.0" encoding="UTF-8"?><meta xmlns="urn:xmind:xmap:xmlns:meta:2.0" version="2.0"/>'
    manifest_xml = """<?xml version="1.0" encoding="UTF-8"?>
<manifest xmlns="urn:xmind:xmap:xmlns:manifest:1.0">
  <file-entry full-path="content.xml" media-type="text/xml"/>
  <file-entry full-path="META-INF/manifest.xml" media-type="text/xml"/>
  <file-entry full-path="meta.xml" media-type="text/xml"/>
</manifest>"""

    buf = BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("content.xml", content_xml)
        zf.writestr("meta.xml", meta_xml)
        zf.writestr("META-INF/manifest.xml", manifest_xml)
    return buf.getvalue()


def to_graphml(results: dict, username: str) -> str:
    found = {p: r for p, r in results.items() if r.get("status") == "FOUND"}
    esc = lambda x: htmlmod.escape(str(x), quote=True)
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<graphml xmlns="http://graphml.graphdrawing.org/xmlns">',
        '<key id="url" for="node" attr.name="url" attr.type="string"/>',
        '<key id="confidence" for="node" attr.name="confidence" attr.type="int"/>',
        '<key id="category" for="node" attr.name="category" attr.type="string"/>',
        f'<graph id="{esc(username)}" edgedefault="undirected">',
        f'<node id="{esc(username)}"><data key="url">seed</data></node>',
    ]
    for p, r in found.items():
        lines.append(
            f'<node id="{esc(p)}">'
            f'<data key="url">{esc(r["url"])}</data>'
            f'<data key="confidence">{r.get("confidence", 0)}</data>'
            f'<data key="category">{esc(r.get("category", ""))}</data></node>'
        )
        lines.append(f'<edge source="{esc(username)}" target="{esc(p)}"/>')
    lines += ["</graph>", "</graphml>"]
    return "\n".join(lines)


def to_neo4j(results: dict, username: str) -> str:
    found = {p: r for p, r in results.items() if r.get("status") == "FOUND"}
    lines = [
        f"// Argis Neo4j import for @{username}",
        f"CREATE (u:Person {{handle: '{username}'}});",
        "",
    ]
    for p, r in found.items():
        safe_p = p.replace("'", "\\'")
        url = r['url'].replace("'", "\\'")
        conf = r.get('confidence', 0)
        cat = r.get('category', 'uncategorized')
        lines.append(
            f"CREATE (n:Account {{platform: '{safe_p}', url: '{url}', "
            f"confidence: {conf}, category: '{cat}'}});"
        )
        lines.append(
            f"MATCH (u:Person {{handle: '{username}'}}), (n:Account {{platform: '{safe_p}'}}) "
            f"CREATE (u)-[:HAS_ACCOUNT]->(n);"
        )
    email_map: dict[str, list[str]] = {}
    for p, r in found.items():
        for e in r.get("emails", []):
            email_map.setdefault(e, []).append(p)
    for email, platforms in email_map.items():
        if len(platforms) > 1:
            lines.append(f"\n// Shared email: {email}")
            for p in platforms:
                safe_p = p.replace("'", "\\'")
                safe_email = email.replace("'", "\\'")
                lines.append(
                    f"MATCH (n:Account {{platform: '{safe_p}'}}) "
                    f"SET n.email = '{safe_email}';"
                )
    return "\n".join(lines)


def to_pdf(results: dict, username: str, html_content: str, out_path: Path) -> bool:
    """Render HTML to PDF. Tries weasyprint, then playwright."""
    try:
        from weasyprint import HTML
        HTML(string=html_content).write_pdf(str(out_path))
        return True
    except Exception:
        pass
    try:
        import asyncio
        from playwright.async_api import async_playwright
        async def _run():
            async with async_playwright() as pw:
                b = await pw.chromium.launch(headless=True)
                pg = await b.new_page()
                await pg.set_content(html_content, wait_until="networkidle")
                await pg.pdf(path=str(out_path), format="A4", print_background=True)
                await b.close()
        asyncio.run(_run())
        return True
    except Exception:
        return False


FORMATTERS = {
    "json": lambda results, username: to_json(results),
    "csv": lambda results, username: to_csv(results),
    "markdown": to_markdown,
    "html": to_html,
    "txt": to_txt,
    "ndjson": to_ndjson,
    "graphml": to_graphml,
    "neo4j": to_neo4j,
}


def export_results(results: dict[str, dict], username: str, fmt: str, out_path: Path) -> Path:
    formatter = FORMATTERS.get(fmt)
    if formatter is None:
        raise ValueError(f"Unsupported export format: {fmt}")
    content = formatter(results, username)
    out_path.write_text(content, encoding="utf-8")
    return out_path


def to_json_stream(results: dict[str, dict]) -> str:
    lines = []
    for name, info in sorted(results.items()):
        entry = {"platform": name, **info}
        lines.append(json.dumps(entry))
    return "\n".join(lines)


async def send_webhook(
    url: str,
    results: dict[str, dict],
    username: str,
    webhook_type: str = "slack",
) -> bool:
    found = sum(1 for r in results.values() if r["status"] == "FOUND")
    total = len(results)

    if webhook_type == "slack":
        payload = {
            "text": f"*Argis scan complete — @{username}*\n> {found}/{total} platforms found",
            "attachments": [
                {
                    "color": "good" if found > 0 else "warning",
                    "fields": [
                        {"title": "Username", "value": username, "short": True},
                        {"title": "Profiles Found", "value": str(found), "short": True},
                        {"title": "Total Scanned", "value": str(total), "short": True},
                    ],
                }
            ],
        }
    elif webhook_type == "discord":
        color = 0x22C55E if found > 0 else 0xF97316
        payload = {
            "embeds": [
                {
                    "title": f"Argis scan — @{username}",
                    "color": color,
                    "fields": [
                        {"name": "Username", "value": username, "inline": True},
                        {"name": "Profiles Found", "value": str(found), "inline": True},
                        {"name": "Total Scanned", "value": str(total), "inline": True},
                    ],
                    "footer": {"text": "Argis OSINT Scanner"},
                }
            ]
        }
    else:
        payload = {
            "username": username,
            "found": found,
            "total": total,
            "results": {k: v["status"] for k, v in results.items()},
        }

    async with httpx.AsyncClient(timeout=10.0) as client:
        try:
            resp = await client.post(url, json=payload)
            return resp.is_success
        except httpx.RequestError:
            return False
