from __future__ import annotations

PLATFORM_DEFAULTS: dict[str, dict] = {
    "github": {
        "url_template": "https://github.com/{}",
        "api": "https://api.github.com/users/{}",
        "category": "code",
        "detection": {"github.com"},
    },
    "gitlab": {
        "url_template": "https://gitlab.com/{}",
        "api": None,
        "category": "code",
    },
    "bitbucket": {
        "url_template": "https://bitbucket.org/{}/",
        "api": "https://api.bitbucket.org/2.0/users/{}",
        "category": "code",
    },
    "instagram": {
        "url_template": "https://www.instagram.com/{}/",
        "api": None,
        "category": "social",
        "private_detect": True,
        "detection": {"instagram.com"},
    },
    "reddit": {
        "url_template": "https://www.reddit.com/user/{}",
        "api": "https://www.reddit.com/user/{}/about.json",
        "category": "social",
        "detection": {"reddit.com"},
    },
    "youtube": {
        "url_template": "https://www.youtube.com/@{}",
        "api": None,
        "category": "video",
        "detection": {"youtube.com"},
    },
    "twitter": {
        "url_template": "https://twitter.com/{}",
        "api": None,
        "category": "social",
        "detection": {"twitter.com", "x.com"},
    },
    "soundcloud": {
        "url_template": "https://soundcloud.com/{}",
        "api": None,
        "category": "music",
        "detection": {"soundcloud.com"},
    },
    "steam": {
        "url_template": "https://steamcommunity.com/id/{}",
        "api": "https://steamcommunity.com/id/{}/?xml=1",
        "category": "gaming",
        "detection": {"steamcommunity.com"},
    },
    "snapchat": {
        "url_template": "https://www.snapchat.com/add/{}",
        "api": None,
        "category": "social",
        "detection": {"snapchat.com"},
    },
    "discord": {
        "url_template": "https://discord.com/users/{}",
        "api": None,
        "category": "social",
    },
    "twitch": {
        "url_template": "https://www.twitch.tv/{}",
        "api": "https://gql.twitch.tv/gql",
        "category": "video",
        "detection": {"twitch.tv"},
    },
    "tiktok": {
        "url_template": "https://www.tiktok.com/@{}",
        "api": None,
        "category": "social",
        "detection": {"tiktok.com"},
    },
    "mastodon": {
        "url_template": "https://{domain}/@{}",
        "api": None,
        "category": "social",
        "requires_instance": True,
    },
    "telegram": {
        "url_template": "https://t.me/{}",
        "api": None,
        "category": "social",
        "detection": {"t.me", "telegram.me"},
    },
    "whatsapp": {
        "url_template": "https://wa.me/{}",
        "api": None,
        "category": "social",
    },
    "signal": {
        "url_template": "https://signal.me/{}",
        "api": None,
        "category": "social",
    },
    "facebook": {
        "url_template": "https://www.facebook.com/{}",
        "api": None,
        "category": "social",
        "detection": {"facebook.com"},
    },
    "linkedin": {
        "url_template": "https://www.linkedin.com/in/{}",
        "api": None,
        "category": "professional",
        "detection": {"linkedin.com"},
    },
    "pinterest": {
        "url_template": "https://www.pinterest.com/{}/",
        "api": None,
        "category": "social",
        "detection": {"pinterest.com"},
    },
    "tumblr": {
        "url_template": "https://{}.tumblr.com",
        "api": None,
        "category": "social",
        "detection": {"tumblr.com"},
    },
    "medium": {
        "url_template": "https://medium.com/@{}",
        "api": None,
        "category": "writing",
        "detection": {"medium.com"},
    },
    "devto": {
        "url_template": "https://dev.to/{}",
        "api": None,
        "category": "code",
        "detection": {"dev.to"},
    },
    "hackernews": {
        "url_template": "https://news.ycombinator.com/user?id={}",
        "api": "https://hacker-news.firebaseio.com/v0/user/{}.json",
        "category": "social",
        "detection": {"ycombinator.com"},
    },
    "keybase": {
        "url_template": "https://keybase.io/{}",
        "api": "https://keybase.io/_/api/1.0/user/lookup.json?usernames={}",
        "category": "security",
        "detection": {"keybase.io"},
    },
    "flickr": {
        "url_template": "https://www.flickr.com/people/{}",
        "api": None,
        "category": "social",
        "detection": {"flickr.com"},
    },
    "500px": {
        "url_template": "https://500px.com/p/{}",
        "api": None,
        "category": "social",
        "detection": {"500px.com"},
    },
    "imgur": {
        "url_template": "https://imgur.com/user/{}",
        "api": None,
        "category": "social",
        "detection": {"imgur.com"},
    },
    "deviantart": {
        "url_template": "https://www.deviantart.com/{}",
        "api": None,
        "category": "social",
        "detection": {"deviantart.com"},
    },
    "behance": {
        "url_template": "https://www.behance.net/{}",
        "api": None,
        "category": "professional",
        "detection": {"behance.net"},
    },
    "dribbble": {
        "url_template": "https://dribbble.com/{}",
        "api": None,
        "category": "professional",
        "detection": {"dribbble.com"},
    },
    "angellist": {
        "url_template": "https://angel.co/u/{}",
        "api": None,
        "category": "professional",
        "detection": {"angel.co"},
    },
    "crunchbase": {
        "url_template": "https://www.crunchbase.com/person/{}",
        "api": None,
        "category": "professional",
        "detection": {"crunchbase.com"},
    },
    "producthunt": {
        "url_template": "https://www.producthunt.com/@{}",
        "api": None,
        "category": "professional",
        "detection": {"producthunt.com"},
    },
    "indiehackers": {
        "url_template": "https://www.indiehackers.com/user/{}",
        "api": None,
        "category": "professional",
        "detection": {"indiehackers.com"},
    },
    "tripadvisor": {
        "url_template": "https://www.tripadvisor.com/members/{}",
        "api": None,
        "category": "travel",
        "detection": {"tripadvisor.com"},
    },
    "airbnb": {
        "url_template": "https://www.airbnb.com/users/show/{}",
        "api": None,
        "category": "travel",
        "detection": {"airbnb.com"},
    },
    "patreon": {
        "url_template": "https://www.patreon.com/{}",
        "api": None,
        "category": "social",
        "detection": {"patreon.com"},
    },
    "buymeacoffee": {
        "url_template": "https://www.buymeacoffee.com/{}",
        "api": None,
        "category": "social",
        "detection": {"buymeacoffee.com"},
    },
    "ko_fi": {
        "url_template": "https://ko-fi.com/{}",
        "api": None,
        "category": "social",
        "detection": {"ko-fi.com"},
    },
    "crowdfunder": {
        "url_template": "https://www.crowdfunder.co.uk/{}",
        "api": None,
        "category": "professional",
        "detection": {"crowdfunder.co.uk"},
    },
    "f6s": {
        "url_template": "https://www.f6s.com/{}",
        "api": None,
        "category": "professional",
        "detection": {"f6s.com"},
    },
    "aboutme": {
        "url_template": "https://about.me/{}",
        "api": None,
        "category": "social",
        "detection": {"about.me"},
    },
    "gravatar": {
        "url_template": "https://gravatar.com/{}",
        "api": "https://api.gravatar.com/{}.json",
        "category": "social",
        "detection": {"gravatar.com"},
    },
    "myanimelist": {
        "url_template": "https://myanimelist.net/profile/{}",
        "api": None,
        "category": "social",
        "detection": {"myanimelist.net"},
    },
    "anilist": {
        "url_template": "https://anilist.co/user/{}",
        "api": None,
        "category": "social",
        "detection": {"anilist.co"},
    },
    "spotify": {
        "url_template": "https://open.spotify.com/user/{}",
        "api": None,
        "category": "music",
        "detection": {"spotify.com"},
    },
    "bandcamp": {
        "url_template": "https://{}.bandcamp.com",
        "api": None,
        "category": "music",
        "detection": {"bandcamp.com"},
    },
    "lastfm": {
        "url_template": "https://www.last.fm/user/{}",
        "api": "https://ws.audioscrobbler.com/2.0/?method=user.getinfo&user={}&format=json",
        "category": "music",
        "detection": {"last.fm"},
    },
    "mixcloud": {
        "url_template": "https://www.mixcloud.com/{}/",
        "api": None,
        "category": "music",
        "detection": {"mixcloud.com"},
    },
    "reverbnation": {
        "url_template": "https://www.reverbnation.com/{}",
        "api": None,
        "category": "music",
        "detection": {"reverbnation.com"},
    },
    "roblox": {
        "url_template": "https://www.roblox.com/user.aspx?username={}",
        "api": "https://users.roblox.com/v1/usernames/users",
        "category": "gaming",
        "detection": {"roblox.com"},
    },
    "chess": {
        "url_template": "https://www.chess.com/member/{}",
        "api": "https://api.chess.com/pub/player/{}",
        "category": "gaming",
        "detection": {"chess.com"},
    },
    "lichess": {
        "url_template": "https://lichess.org/@/{}",
        "api": "https://lichess.org/api/user/{}",
        "category": "gaming",
        "detection": {"lichess.org"},
    },
    "speedrun": {
        "url_template": "https://www.speedrun.com/users/{}",
        "api": None,
        "category": "gaming",
        "detection": {"speedrun.com"},
    },
    "epicgames": {
        "url_template": "https://www.epicgames.com/id/{}",
        "api": None,
        "category": "gaming",
        "detection": {"epicgames.com"},
    },
    "xbox": {
        "url_template": "https://account.xbox.com/en-us/profile?gamertag={}",
        "api": None,
        "category": "gaming",
        "detection": {"xbox.com"},
    },
    "psn": {
        "url_template": "https://psnprofiles.com/{}",
        "api": None,
        "category": "gaming",
        "detection": {"psnprofiles.com"},
    },
    "nintendo": {
        "url_template": "https://en-americas-support.nintendo.com/app/userlist/{}",
        "api": None,
        "category": "gaming",
        "detection": {"nintendo.com"},
    },
    "hackerone": {
        "url_template": "https://hackerone.com/{}",
        "api": None,
        "category": "security",
        "detection": {"hackerone.com"},
    },
    "bugcrowd": {
        "url_template": "https://bugcrowd.com/{}",
        "api": None,
        "category": "security",
        "detection": {"bugcrowd.com"},
    },
    "intigriti": {
        "url_template": "https://app.intigriti.com/researcher/profile/{}",
        "api": None,
        "category": "security",
        "detection": {"intigriti.com"},
    },
    "tryhackme": {
        "url_template": "https://tryhackme.com/p/{}",
        "api": None,
        "category": "security",
        "detection": {"tryhackme.com"},
    },
    "hackthebox": {
        "url_template": "https://app.hackthebox.com/users/{}",
        "api": None,
        "category": "security",
        "detection": {"hackthebox.com"},
    },
    "virustotal": {
        "url_template": "https://www.virustotal.com/gui/user/{}",
        "api": None,
        "category": "security",
        "detection": {"virustotal.com"},
    },
    "abuseipdb": {
        "url_template": "https://www.abuseipdb.com/user/{}",
        "api": None,
        "category": "security",
        "detection": {"abuseipdb.com"},
    },
    "shodan": {
        "url_template": "https://account.shodan.io/{}",
        "api": None,
        "category": "security",
        "detection": {"shodan.io"},
    },
    "wikipedia": {
        "url_template": "https://en.wikipedia.org/wiki/User:{}",
        "api": None,
        "category": "reference",
        "detection": {"wikipedia.org"},
    },
    "wikidata": {
        "url_template": "https://www.wikidata.org/wiki/User:{}",
        "api": None,
        "category": "reference",
        "detection": {"wikidata.org"},
    },
    "wikimedia": {
        "url_template": "https://meta.wikimedia.org/wiki/User:{}",
        "api": None,
        "category": "reference",
        "detection": {"wikimedia.org"},
    },
    "archive": {
        "url_template": "https://archive.org/details/@{}",
        "api": "https://archive.org/metadata/@{}",
        "category": "reference",
        "detection": {"archive.org"},
    },
    "codepen": {
        "url_template": "https://codepen.io/{}",
        "api": "https://codepen.io/api/profiles/{}",
        "category": "code",
        "detection": {"codepen.io"},
    },
    "replit": {
        "url_template": "https://replit.com/@{}",
        "api": None,
        "category": "code",
        "detection": {"replit.com"},
    },
    "stackoverflow": {
        "url_template": "https://stackoverflow.com/users/-/{}",
        "api": None,
        "category": "code",
        "detection": {"stackoverflow.com"},
    },
    "stackexchange": {
        "url_template": "https://stackexchange.com/users/-/{}",
        "api": None,
        "category": "code",
        "detection": {"stackexchange.com"},
    },
    "quora": {
        "url_template": "https://www.quora.com/profile/{}",
        "api": None,
        "category": "social",
        "detection": {"quora.com"},
    },
    "slideshare": {
        "url_template": "https://www.slideshare.net/{}",
        "api": None,
        "category": "professional",
        "detection": {"slideshare.net"},
    },
    "issuu": {
        "url_template": "https://issuu.com/{}",
        "api": None,
        "category": "professional",
        "detection": {"issuu.com"},
    },
    "scribd": {
        "url_template": "https://www.scribd.com/{}",
        "api": None,
        "category": "social",
        "detection": {"scribd.com"},
    },
    "academia": {
        "url_template": "https://independent.academia.edu/{}",
        "api": None,
        "category": "professional",
        "detection": {"academia.edu"},
    },
    "researchgate": {
        "url_template": "https://www.researchgate.net/profile/{}",
        "api": None,
        "category": "professional",
        "detection": {"researchgate.net"},
    },
    "orcid": {
        "url_template": "https://orcid.org/{}",
        "api": None,
        "category": "professional",
        "detection": {"orcid.org"},
    },
    "googlescholar": {
        "url_template": "https://scholar.google.com/citations?user={}",
        "api": None,
        "category": "professional",
        "detection": {"scholar.google.com"},
    },
    "loop": {
        "url_template": "https://loop.frontiersin.org/people/{}",
        "api": None,
        "category": "professional",
        "detection": {"loop.frontiersin.org"},
    },
    "impactstory": {
        "url_template": "https://impactstory.org/u/{}",
        "api": None,
        "category": "professional",
        "detection": {"impactstory.org"},
    },
    "pubmed": {
        "url_template": "https://pubmed.ncbi.nlm.nih.gov/?term={}",
        "api": None,
        "category": "professional",
        "detection": {"pubmed.ncbi.nlm.nih.gov"},
    },
    "dblp": {
        "url_template": "https://dblp.uni-trier.de/pid/{}",
        "api": None,
        "category": "professional",
        "detection": {"dblp.uni-trier.de"},
    },
}

BUILTIN_PLATFORMS: tuple[str, ...] = tuple(PLATFORM_DEFAULTS.keys())
